### ISSUE TITLE
nsfw packs are not limited to nsfw channels 

### ISSUE THREAD

**Issue by ker0olos** [ker0olos/fable#120]
if the pack is marked as NSFW and the channel is not then filter the entire pack out

**Comment by thealoneshadow** [comment]
If a pack is marked as NSFW (Not Safe For Work) and the channel is not, it would be advisable to filter out the entire pack to ensure that inappropriate content is not displayed in a channel where it is not appropriate or welcomed. NSFW content may contain explicit or suggestive material that is not suitable for all audiences, and it is important to respect the boundaries and preferences of different communities and individuals. Filtering out the entire pack can help maintain a safe and respectful environment in the channel.

**Comment by ker0olos** [comment]
> If a pack is marked as NSFW (Not Safe For Work) and the channel is not, it would be advisable to filter out the entire pack to ensure that inappropriate content is not displayed in a channel where it is not appropriate or welcomed. NSFW content may contain explicit or suggestive material that is not suitable for all audiences, and it is important to respect the boundaries and preferences of different communities and individuals. Filtering out the entire pack can help maintain a safe and respectful environment in the channel.

Thank you, chatgpt.
