### ISSUE TITLE
Cheating with pulls

### ISSUE THREAD

**Issue by B331Z380085W338x0x0** [ker0olos/fable#408]
**People can pull more times than available**

Since Discord's update to merge bots with apps there is UI that allows to run commands and you can sometimes pull more times with it.

**To Reproduce**

1. Do 1-2 pulls with "/q", "/wa", etc
2. Open command's UI in mobile app
3. Tap button "Send" as much as possible
4. 6 pulls instead of 5

**Expected behavior**

Pull limits shouldn't be ignored

**Screenshots**

none

**Any additional context**

mentioned in the commands channel of dev's server in Discord

**Comment by ker0olos** [comment]
Hi, Beelz. You know it's weird because the code should always check the database and confirm you have enough pulls before adding the character. Anyway yeah I will try to fix it soon.

**Comment by B331Z380085W338x0x0** [comment]
> Hi, Beelz. You know it's weird because the code should always check the database and confirm you have enough pulls before adding the character. Anyway yeah I will try to fix it soon.

Now I'm not really sure if it can be prevented on the bot side. Because mostly I can reproduce it with new Discord's mobile UI.

**Comment by ker0olos** [comment]
I will make time to try and figure this out today, I'll let you know.
